"""Fix

Revision ID: 272b81271fc9
Revises: d6d27b64d063
Create Date: 2024-04-28 01:36:09.863621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272b81271fc9'
down_revision: Union[str, None] = 'd6d27b64d063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('travels', 'path_to_image',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('travels', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('travels', 'path_to_image',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
