"""Delete email

Revision ID: 12844d1ca8a2
Revises: 4854420b1178
Create Date: 2024-04-27 16:17:12.355089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12844d1ca8a2'
down_revision: Union[str, None] = '4854420b1178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unused_votes', sa.Integer(), nullable=True))
    op.drop_column('users', 'email')
    op.drop_column('users', 'email_verified')
    op.drop_column('votes', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('users', 'unused_votes')
    # ### end Alembic commands ###
