"""Some fix

Revision ID: cf2906032cb3
Revises: 527b0b872445
Create Date: 2024-04-27 22:08:55.902419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2906032cb3'
down_revision: Union[str, None] = '527b0b872445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_votes_users_id_user_id', 'votes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_votes_users_id_user_id', 'votes', 'users', ['user_id'], ['id'])
    op.alter_column('votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
