"""fix

Revision ID: 2b3c637c9376
Revises: 4854420b1178
Create Date: 2024-04-27 17:04:27.982642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3c637c9376'
down_revision: Union[str, None] = '4854420b1178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('votes', sa.Integer(), nullable=True))
    op.drop_constraint('fk_payments_votes_id_vote_id', 'payments', type_='foreignkey')
    op.drop_column('payments', 'vote_id')
    op.add_column('users', sa.Column('unused_votes', sa.Integer(), nullable=True))
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'email')
    op.drop_column('votes', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'unused_votes')
    op.add_column('payments', sa.Column('vote_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_payments_votes_id_vote_id', 'payments', 'votes', ['vote_id'], ['id'])
    op.drop_column('payments', 'votes')
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###
