"""Returned amount

Revision ID: 0545cabfa9e2
Revises: e2f327d85503
Create Date: 2024-04-27 18:31:59.352830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0545cabfa9e2'
down_revision: Union[str, None] = 'e2f327d85503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'amount')
    # ### end Alembic commands ###
